monitio/urls.py
from django.conf.urls import patterns, url
from django.views.i18n import javascript_catalog
from monitio.views import SameUserChannelRedisQueueView

js_info_dict = {
    'domain': 'djangojs',
    'packages': ('monitio',),
}
urlpatterns = patterns(
    'monitio.views',


    # Mark read
    url(r'^mark_read/(?P<message_id>\d+)/$', 'message_mark_read',
        name='message_mark_read'),
    url(r'^mark_read/all/$', 'message_mark_all_read',
        name='message_mark_all_read'),

    # Delete
    url(r'^delete/message/(?P<message_id>\d+)/$', 'message_delete',
        name='message_delete'),
    url(r'^delete/all/$', 'message_delete_all', name='message_delete_all'),

    # Get via json
    url(r'^json/$', 'messages_json', name='message_json'),

    # django-sse
    url(r'^sse/(?P<channel>\w+)?$',
        SameUserChannelRedisQueueView.as_view(), name="persistent-messages-sse"),

    # i18n
    url(r'^jsi18n/$',
        javascript_catalog, # 'django.views.i18n.javascript_catalog',
        js_info_dict,
        name="js_i18n"),

)

test_project/urls.py
from django.conf.urls import patterns, url, include
from django.contrib import admin

from test_app.views import TestView
from test_app.views import TestFoundationView

admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', TestView.as_view(), name='index'),
    url(r'^foundation/$', TestFoundationView.as_view(), name='foundation'),
    url(r'^messages/', include('monitio.urls', namespace="monitio"))
)

test_app/models.py
from django.db import models

# Create your models here.

test_app/views.py
# Create your views here.
from django.views.generic import TemplateView


class TestView(TemplateView):
    template_name = 'test_app/index.html'

class TestFoundationView(TemplateView):
    template_name = 'test_app/foundation_index.html'

test_app/templates/test_app/foundation_index.html
{# mark_as_read_by_url automatically marks all messages with #}
{# url = request.get_full_path and user=request.user as READ #}
{# So, when you click a specific page, it can autmatically close #}
{# some messages. #}
{% load mark_as_read_by_url %}
{% mark_as_read_by_url %}<!DOCTYPE html>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>monitio on Foundation 5</title>


    <link rel="stylesheet"
          href="http://cdnjs.cloudflare.com/ajax/libs/foundation/5.0.2/css/normalize.css">
    <link rel="stylesheet"
          href="http://cdnjs.cloudflare.com/ajax/libs/foundation/5.0.2/css/foundation.css">


    <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>

    {% include "monitio/header.html" %}

</head>
<body>

<!-- body content here -->
<div class="row columns">
    <div class="large-12"><p>
        Hi. Messages placeholder below. This demo uses <a
            href="http://foundation.zurb.com/">Foundation 5 library</a>.
        </p>
    </div>
    <div class="large-12">
        <div id="monitioMessages"></div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $(document).foundation();



        $("#monitioMessages").MessagesPlaceholder({
            "url": '{% url "monitio:persistent-messages-sse" user.username %}',
            "theme": "foundation"
        });

    });
</script>
<!-- because of http://stackoverflow.com/questions/20140710/foundation-5-upgrade-layer-must-be-a-document-node
 we are putting those files here and not in the header section. -->
<script src="http://cdnjs.cloudflare.com/ajax/libs/foundation/5.0.2/js/vendor/custom.modernizr.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/foundation/5.0.2/js/foundation.min.js"></script>
</body>
</html>

test_app/templates/test_app/index.html
{# mark_as_read_by_url automatically marks all messages with #}
{# url = request.get_full_path and user=request.user as READ #}
{# So, when you click a specific page, it can autmatically close #}
{# some messages. #}
{% load mark_as_read_by_url %}
{% mark_as_read_by_url %}<!DOCTYPE html>
<html>
<head>
    <title>django-monitio demo</title>

    <!-- jquery from CDN and CSS for it -->
    <script type="text/javascript"
            src="http://code.jquery.com/jquery-1.9.1.js"></script>
    <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
    <link rel="stylesheet"
          href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css"/>

    {% include "monitio/header.html" %}
</head>

<body style="width: 600px; margin-left: auto; margin-right: auto;">
<p>
    Hi. Thank you for testing this software! Messages placeholder can be found
    below this line. If there are no messages, read on to learn, how to
    send offline live messages to this web page.

<div id="monitioMessages"></div>
<p style="margin-left: 5em; font-style: italic; font-size: 0.8em;">
    If you like, you can try <a href="./foundation/">Foundation 5 demo</a>
    instead. If you do, please remember, that all the instructions
    below also apply to <a href="./foundation/">Foundation 5 demo</a>!
</p>
</p>

{% if request.user.is_anonymous %}
    <p>
        You are <strong>not</strong> logged in. Please go to the <a
            href="/admin/">admin</a>
        and
        log in (as test/test). </p>

    <p>Then, please come back to this page - you will get additional
        instructions on
        how to test dynamic notifications messages.
    </p>
{% else %}
    Go to the command prompt and run:
    <pre>
    $ manage.py send_message [from user] [to user] [INFO|ERROR] [message]
</pre>
    for example:
    <pre>
    $ manage.py send_message test test INFO "This is a test message"
    $ manage.py send_message test test SUCCESS "This is a success message"
    $ manage.py send_message test test WARNING "This is a warning message"
    </pre>
    <strong>Make sure you are runing Redis</strong> on 127.0.0.1:6379 before
    issuing that command.
    <p>
        This will create a persistent message, that will be displayed at once
        (via SSE), and will stay displayed when you refresh this page. You will
        need to close it for it to stop displaying.
    </p>
    <p/>
    ... or, if you want just to play with SSE - aka "the cool stuff":
    <pre>
   $ manage.py sse_test test
</pre>
    -- to send dynamic notifications to user 'test'. Even anonymous users could
    receive SSE notifications, but currently, as I see no point in it, there
    is no support for them.<p>
    That's all. Now go and have fun! :-)
</p>
    <script type="application/javascript">
        $(document).ready(function () {

            initial = [];
            {% if messages %}
                {% for message in messages %}
                    initial.push({
                        'subject': '{{ message.subject }}',
                        'message': '{{ message.message }}',
                        'level': '{{ message.level }}',
                        'url': '{{ message.url }}',
                        'is_persistent': {{ message.is_persistent|lower }},
                        'pk': '{{ message.pk }}'});
                {% endfor %}
            {% endif %}

            $("#monitioMessages").MessagesPlaceholder({
                "url": '{% url "monitio:persistent-messages-sse" user.username %}',
                "initial": initial
            });
        });
    </script>
{% endif %}
</body>
</html